config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_for :users
  resources :notes

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  has_enumeration_for :priority, with: Priority, create_helpers: true

  validates :title, presence: true
  validates :content, presence: true
  validates :priority, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :notes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  layout :layout_authentication

  protected

  def layout_authentication
    'authentication' if devise_controller?
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_params, only: %i[show edit update destroy]

  def index
    @notes = Note.all
  end

  def show; end

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.build(notes_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @note.update(notes_params)
        format.html { redirect_to notes_path, notice: 'Note was successfully updated.' }
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
    end
  end

  private

  def set_params
    @note = Note.find(params[:id])
  end

  def notes_params
    params.require(:note).permit(:title, :content, :priority)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
# frozen_string_literal: true

# devise helper
module DeviseHelper
  def devise_error_messages!
    return if resource.errors.empty?

    messages = resource.errors.full_messages.map do |msg|
      content_tag(:p, "- #{msg}.")
    end.join
    sentence = I18n.t('errors.messages.not_saved',
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
      <div class="bg-red-100 border-l-4 border-red-500 mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">Oops!</p>
          <p>#{sentence}</p>#{messages}
      </div>
    HTML

    html.html_safe
  end

  def devise_simple_error_messages!
    return if resource.errors.empty?

    sentence = 'Ooops!'
    if resource.errors.count == 1
      message =  resource.errors.full_messages[0]
      html = <<-HTML
        <div class="bg-red-lightest border-l-4 border-red text-orange-dark p-4" role="alert">
          <p class="font-bold">#{sentence}</p>
          <p> #{message}.</p>
        </div>
      HTML
    else
      messages = resource.errors.full_messages.map do |msg|
        content_tag(:li, "#{msg}.")
      end.join
      html = <<-HTML
        <div class="bg-red-100 border-l-4 border-red-500  mb-4 p-4 text-red-700" role="alert">
          <p class="font-bold">#{sentence}</p>
          <ul class="list-disc">
            #{messages}
          </ul>
        </div>
      HTML
    end

    html.html_safe
  end
end

app/helpers/heroicon_helper.rb
# frozen_string_literal: true

module HeroiconHelper
  include Heroicon::Engine.helpers
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.slim
doctype html
html
  head
    title w3n templates
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body class='bg-cyan-50'
    main class='flex flex-col h-screen'
      header
        = render 'shared/menubar'
      section class='flex-1 mt-16 md:pt-2'
        article class='flex items-center justify-center h-full'
          = yield
      section class='flex justify-center text-gray-500 text-sm my-4'
        | w3n &copy; 2023. All rights reserved.

app/views/layouts/authentication.html.slim
doctype html
html
  head
    title Sign In
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body class='bg-blue-50'
    main class='w-full h-screen flex justify-center items-center'
      = yield

app/views/notes/_form.html.slim
= simple_form_for note, html: { class: 'mt-4 space-y-4' } do |f|
        = f.input :title, label: false, input_html: { class: 'w-full border-gray-300 rounded-lg shadow placeholder:text-gray-400 focus:ring-0', placeholder: 'add new title ...' }
        = f.input :content, label: false, as: :text, input_html: { class: 'w-full h-28 border-gray-300 rounded-lg shadow placeholder:text-gray-400 focus:ring-0', placeholder: 'add your description...' }
        = f.input :priority, label: false, collection: Priority.list, include_blank: false, input_html: { class: 'border-gray-300 rounded-lg shadow placeholder:text-gray-400 focus:ring-0' }
        = f.submit class: 'bg-sky-500 text-white px-4 py-2 rounded-lg shadow hover:bg-sky-600 transition'

app/views/notes/_note.html.slim
div class='bg-white rounded-lg shadow-lg p-4 flex flex-col gap-3'
  div class='flex justify-between items-start'
    span class='text-xs px-2 py-1 bg-gray-300 rounded-full'
      = note.priority
    span
      = heroicon 'ellipsis-horizontal', options: { class: 'h-5 w-5 text-gray-500' }
  div class='flex-1'
    h2 class='text-md font-semibold md:text-xl leading-tight'
      = link_to note.title, note, class: 'text-gray-800 hover:text-sky-500'
    p class='text-sm text-gray-500 mt-2'
      == truncate note.content, length: 100
  div
    small class='text-gray-400 text-right block tracking-tight'
      = note.created_at.strftime('%d %b %Y')

app/views/notes/edit.html.slim
section class='h-full container mx-auto'
  div class='flex w-full justify-center'
    div class='w-3/5 mt-16'
      = link_to sanitize("&larr; back to notes"), notes_path, class: 'text-sky-500 text-sm font-medium mb-4 text-right block'
      h1 class='text-3xl font-bold text-gray-800' Edit Note
      = render 'form', note: @note

app/views/notes/index.html.slim
section class='h-full w-full bg-cyan-50 relative'
  div class='fixed w-full bg-sky-500 border-t-2 border-sky-600 px-2 py-2 lg:px-4 text-white'
    div class='flex justify-between items-center gap-3'
      div class='flex items-center gap-3 bg-white rounded px-2 py-2 text-sm text-sky-500'
        span class='text-sm font-medium hidden md:block' sort by date:
        = heroicon 'bars-arrow-down', options: { class: 'h-6 w-6' }
        = heroicon 'bars-arrow-up', options: { class: 'h-6 w-6' }
      div class='md:w-2/5 md:hidden'
        = simple_form_for :search, url: notes_path, html:{} do |f|
          = f.input :query, label: false, input_html: { class: 'w-full bg-white text-sm text-gray-800 px-4 py-2 rounded flex items-center border-white focus:ring-0 transition', placeholder: 'Search Notes' }
      div
        =link_to new_note_path, class: 'bg-white text-sky-500 md:px-4 px-2 py-2 rounded flex items-center border hover:border-white hover:bg-sky-500 hover:text-white transition' do
          = heroicon 'document-plus', options: { class: 'h-6 w-6 md:pr-2' }
          span class='text-sm font-medium hidden md:block' New Note
  div class='grid grid-cols-2 md:grid-cols-4 gap-4 p-4 mt-16'
    =render @notes

app/views/notes/new.html.slim
section class='h-full container mx-auto'
  div class='flex w-full justify-center'
    div class='w-3/5 mt-16'
      = link_to sanitize("&larr; back to notes"), notes_path, class: 'text-sky-500 text-sm font-medium mb-4 text-right block'
      h1 class='text-3xl font-bold text-gray-800' New Note
      = render 'form', note: @note

app/views/notes/show.html.slim
section class='h-full container mx-auto'
  div class='flex w-full justify-center mb-8'
    div class='w-3/5 mt-16 space-y-8'
      = link_to sanitize("&larr; back to notes"), notes_path, class: 'text-sky-500 text-sm font-medium mb-4 text-right block'
      span class='bg-sky-500 text-white text-xs font-medium px-4 py-1 rounded-full'
        = heroicon 'flag', options: { class: 'h-5 w-5 inline' }
        = @note.priority
      h1 class='text-3xl font-bold text-gray-800 leading-8'
        = @note.title
      span class='text-gray-400 text-sm'
        = @note.user.email
      p class='text-gray-600 text-sm mb-4'
        = @note.content
      p class='text-gray-600 text-sm flex items-center gap-2'
        span
          = heroicon 'calendar', options: { class: 'h-5 w-5 text-gray-500 inline-block' }
        = @note.created_at.strftime('%B %d, %Y')

      div class='flex gap-2'
        = link_to 'Edit', edit_note_path(@note), class: 'text-sm text-white bg-sky-500 hover:bg-sky-600 rounded-lg px-4 py-2'
        = link_to 'Delete', note_path(@note), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'text-sm text-white bg-red-500 hover:bg-red-600 rounded-lg px-4 py-2'

app/views/pages/home.html.slim
div class='w-full lg:w-2/5 relative'
  div class='flex justify-center'
    div class='flex flex-col'
      = heroicon 'swatch', options:{class: 'h-16 w-16 block text-sky-500 mr-2'}
      h1 class='text-5xl lg:text-7xl font-bold text-gray-800'
        = link_to 'talentNotes', root_path
  div
    h4 class='text-xl lg:text-2xl font-light mt-4 text-gray-600 text-center'
      | Mantenha suas anotações, idéias, pensamentos bem guadados e organizados com níveis de prioridate!

app/views/shared/_menubar.html.slim
nav class='fixed w-full bg-white shadow py-4 px-2 lg:px-4 flex items-center justify-between space-x-4 z-10'
  div class='flex items-center'
    = heroicon 'swatch', options:{class: 'h-6 w-6 inline-block text-sky-500 mr-2'}
    h1 class='text-2xl font-bold text-gray-800'
      = link_to 'talentNotes', root_path

  div class='w-2/4 hidden md:block'
    = simple_form_for :search, url: root_path, method: :get, html: { class: 'flex justify-center' } do |f|
      div class='relative w-2/4'
        = f.input :query, label: false, placeholder: 'Pesquisar', input_html: { class: 'bg-gray-50 w-full px-4 py-2 rounded-lg text-sm font-medium text-gray-800 placeholder-gray-500 focus:outline-none focus:shadow-xs inline-block border-gray-300' }
        div class='absolute right-0 top-0 mt-2 mr-2'
          = heroicon 'magnifying-glass', options:{class: 'h-4 w-4 mr-1' }
  div
    - if user_signed_in?
      = link_to destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'bg-red-500 px-4 py-2 rounded-lg text-sm font-semibold text-white hover:bg-red-600' do
        = heroicon 'arrow-right-on-rectangle', options:{class: 'h-4 w-4 inline-block mr-1' }
        = 'Sair'
    - else
      = link_to 'Entrar', new_user_session_path, class: 'bg-sky-500 px-4 py-2 rounded-lg text-sm font-medium text-white hover:bg-sky-600'